### ISSUE TITLE
Error resolving 'gcil.cf': No address associated with hostname

### ISSUE THREAD

**Issue by samdroid-apps** [i5o/GCILeaderboard#27]
That's what my browser says :(

**Comment by tradzik** [comment]
@i5o what is wrong with your server?

**Comment by i5o** [comment]
I will not mantain gcil this year..

Meanwhile it's accesible from here: http://bzflag.bz:54321/

2015-11-23 12:30 GMT-03:00, Tymon Radzik <notifications@github.com>:
> @i5o what is wrong with your server?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/i5o/GCILeaderboard/issues/27#issuecomment-158969420


-- 
Ignacio Rodríguez
SugarLabs at Facebook
<https://www.facebook.com/pages/SugarLabs/187845102582>
