### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by DarkmatterVale** [i5o/GCILeaderboard#28]
I'm unable to get access to the website. Is it not up?

**Comment by tradzik** [comment]
It won't be up this year. Sorry.

pon., 7.12.2015 o 17:49 użytkownik Vale <notifications@github.com> napisał:

**Comment by DarkmatterVale** [comment]
Ah, ok. Is there a way to run it locally?

**Comment by tradzik** [comment]
Yes. You can download it and run, but it might not work as GCI has new
website.

pon., 7.12.2015 o 17:59 użytkownik Vale <notifications@github.com> napisał:

**Comment by DarkmatterVale** [comment]
Yea, I don't think it will. The new site is very different.

Thanks anyway!

**Comment by tradzik** [comment]
@DarkmatterVale You are welcome.
